### ISSUE TITLE
Improper implementation of 'New' button

### ISSUE THREAD

**Issue by GianlucaCorvinelli** [jamiedishy/EECS2311#1]
**Operating System:**
Windows 10

**Java version:**
Version 8 Update 144 (build 1.8.0_144-b01)

**Product Version:**
BrailleAuthoringApp.v1.1

**Component:** 
Menu Bar

**Summary:**
When the user creates a new scenario, it doesn't actually start a new fresh scenario.  It keeps commands from the previously created scenario at the beginning of every newly created scenario. 

**Description:**
Steps to reproduce the bug
1. Click File > New. 
2. Enter a file name and number of Braille cells and click Create.
3. Select any of the 3 options and start adding lines to the text file.
4. Click Save.
5. Click File > New.
6. Enter a unique file name and number of Braille cells and click Create.
7. Repeat steps 3 and 4.
8. Open the file you created in Steps 5 & 6.

_Actual Results_ 
The new scenario file created in step 5 contains content from the previously created scenario in step 1.
_Expected Results_ 
When the New button is clicked, a completely fresh and independant scenario should be created.

**Priority:**
P3

**Severity Value:**
Minor

**Comment by pjsison** [comment]
A really good find.

**The Fix**
Invoked `displayWelcomePage()` method in `newScenario()`. This resets the variables required for a fresh scenario.
