### ISSUE TITLE
Cannot Save Newly Created Scenarios

### ISSUE THREAD

**Issue by marksavin** [jamiedishy/EECS2311#2]
Author: Mark Savin 
Product Version: BrailleAuthoringApp.v1.1 
Component: “Save” and “Save as…” buttons in the file drop down menu 
Platform: Java Version 8 
Operating System: Windows 10 
Bug detected on March 06, 2018 at 10:00 PM

**Summary** 
Cannot save a newly created scenario. 

**Description**  
**Steps to Reproduce**
Create a scenario by selecting file --> New…--> select number of cells and number of buttons --> create. After you are done creating your scenario save it by selecting --> file --> save or save as…. After saving, the newly created scenario should appear in the FactoryScenarios folder, but it does not, indicating that the scenario was not saved. 

**Actual Results**
The newly created scenario was not saved.  

**Expected**
The created scenario should have been saved and stored in the FactoryScenarios folder.

**Severity**
The severity is **major**. If the app cannot save scenarios, then the teacher does not have a way to provide lessons to their students which defeats the purpose of creating the app. Re-creating scenarios every time is not a practical solution and does not make sense. 

**Priority**
**P2**, this is a **high priority**. If the bug does not get resolved, then the teacher will not be able to provide lessons to students and this defeats the purpose of creating the app. This bug also directly affects the functionality to load scenarios. If you can’t save files, then you have nothing to load. However, this bug does not crash the app or harm it in any way. In this regard, fixing it right away is not urgent, but, to have a fully functioning Braille App capable of teaching visually impaired children to learn the alphabet, the save feature is essential.

**Comment by JonasLaya** [comment]
FIXED!

Package ScenarioFolder into same directory as executable.
