### ISSUE TITLE
Broken UI Flow when cancelling from New Scenario dialog

### ISSUE THREAD

**Issue by JonasLaya** [jamiedishy/EECS2311#4]
****Operating System:** Windows 10

**Java Version:** Version 8 Update 73 (build 1.8.0_73-b02)

**Product Version:** AuthoringApp v1.0.0

**Component:** New Scenario Dialog

**Priority:** P5

**Severity Value:** Minor

**Summary:** While working with a current scenario and the user tries to create a new scenario but cancels from the 'New Scenario' dialog box, the UI reverts back to the Scenario Start page.

**Description:**

Steps to reproduce the bug:

1. Create Scenario from the main menu
2. Enter scenario name and number of braille cell and button
3. While on the 'Scenario Editor' page, click 'File' from the menu bar and click 'New...'
4. On 'New Scenario' dialog box, click Cancel.

**Actual Results:** The UI reverts back to the Scenario Start page

**Expected Results:** The 'New Scenario' dialog box closes and the user continues to work with the UI or window the user was on before opening the 'New Scenario' dialog box.

**Comment by jamiedishy** [comment]
Fixed
In NewScenarioDialog.java, added 'header = null' for the EventHandler for the cancel button.
